# -*- coding: utf-8 -*-
"""GenAi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HCiVsUwmHYK0uphQybWR6K_5hDhr4XaH

# Experiment 2 :
"""

import nltk
import json
import string

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')

text ="""
my name is rishi yadav and i am pursuing bachelors in computer science
"""
corpus = text.lower()
print(corpus)

nltk.download('punkt_tab')
tokens = word_tokenize(corpus)
print(tokens)

tokens = [word for word  in tokens if word not in string.punctuation]
print(tokens)

stop_words = set(stopwords.words('english'))

clean_tokens = [word for word in tokens if word not in stop_words]
print(clean_tokens)

vocabulary = sorted(set(clean_tokens))
print(vocabulary)

vocab_dict = {"vocabulary": vocabulary}

with open("vocabulary.json", "w") as file:
    json.dump(vocab_dict, file,indent=4)

print("Vocabulary saved to vocabulary.json")